services:
  admin-backend:
    restart: always
    build:
      context: admin
    ports:
      - "8001:8000"
    environment:
      - url=sqlite:///database.db

  admin-frontend:
    restart: always
    depends_on:
      - admin-backend
    build:
      context: frontend-admin
    ports:
      - "8002:3000"
    environment:
      - BASE_URL=http://admin-backend:8000/api
      - SOCKET_URL=https://ixtream.ngrok.app

  nginx:
    restart: always
    build:
      context: .
    depends_on:
      - admin-backend
      - admin-frontend

    ports:
      - "8003:80"
