services:
  admin-backend:
    restart: always
    build:
      context: admin
    ports:
      - "8001:80"
    environment:
      - url=sqlite:///database.db

  admin-frontend:
    restart: always
    depends_on:
      - admin-backend
    build:
      context: frontend-admin
    ports:
      - "8002:3000"
    environment:
      - BASE_URL=http://admin-backend/backend/api
      - SOCKET_URL=https://ixtream.ngrok.app/backend

  nginx:
    restart: always
    depends_on:
      - admin-backend
      - admin-frontend

    ports:
      - "80:80"
