services:
  admin-backend:
    build:
      context: admin
    ports:
      - "8001:80"
    environment:
      - url=sqlite:///database.db

  admin-frontend:
    depends_on:
      - admin-backend
    build:
      context: frontend-admin
    ports:
      - "8002:3000"
    environment:
      - BASE_URL=http://admin-backend/api
      - SOCKET_URL=http://localhost:8001
