"""start database

Revision ID: 3fef1fb16690
Revises: 
Create Date: 2025-02-25 07:35:34.540502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fef1fb16690'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_radio_station',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('radio_station_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['radio_station_id'], ['radio_station.id'], ),
    sa.PrimaryKeyConstraint('client_id', 'radio_station_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_radio_station')
    # ### end Alembic commands ###
